// lib/defaultData.js

export const DEFAULT_ACTIVITIES = [
  // ========== LEAF ACTIVITIES ==========
  {
    id: "npd",
    label: "📚 NPD",
    type: "leaf",
    target: 10,
    unit: "halaman",
  },
  {
    id: "olahraga",
    label: "🏃 Olahraga",
    type: "leaf",
    target: 7,
    unit: "km",
  },

  // Catatan: "mandarin" udah dihapus (ada di Belajar).
  // Catatan: "fiqih" udah dihapus (ada di Belajar → Agama).

  // ========== HAFALAN QUR'AN ==========
  {
    id: "hafalan",
    label: "📖 Hafalan Qur'an",
    type: "expandable",
    children: [
      // ========== JUZ 1 ==========
      {
        id: "juz_1",
        label: "Juz 1",
        type: "expandable",
        children: [
          { id: "juz1_alfatihah", label: "Al-Fatihah (1-7)", type: "leaf" },
          { id: "juz1_baqarah_1_5", label: "Al-Baqarah (1-5)", type: "leaf" },
          { id: "juz1_baqarah_6_10", label: "Al-Baqarah (6-10)", type: "leaf" },
          { id: "juz1_baqarah_11_15", label: "Al-Baqarah (11-15)", type: "leaf" },
          { id: "juz1_baqarah_16_20", label: "Al-Baqarah (16-20)", type: "leaf" },
          { id: "juz1_baqarah_21_25", label: "Al-Baqarah (21-25)", type: "leaf" },
          { id: "juz1_baqarah_26_30", label: "Al-Baqarah (26-30)", type: "leaf" },
          { id: "juz1_baqarah_31_35", label: "Al-Baqarah (31-35)", type: "leaf" },
          { id: "juz1_baqarah_36_40", label: "Al-Baqarah (36-40)", type: "leaf" },
          { id: "juz1_baqarah_41_45", label: "Al-Baqarah (41-45)", type: "leaf" },
          { id: "juz1_baqarah_46_50", label: "Al-Baqarah (46-50)", type: "leaf" },
          { id: "juz1_baqarah_51_55", label: "Al-Baqarah (51-55)", type: "leaf" },
          { id: "juz1_baqarah_56_60", label: "Al-Baqarah (56-60)", type: "leaf" },
          { id: "juz1_baqarah_61_65", label: "Al-Baqarah (61-65)", type: "leaf" },
          { id: "juz1_baqarah_66_70", label: "Al-Baqarah (66-70)", type: "leaf" },
          { id: "juz1_baqarah_71_75", label: "Al-Baqarah (71-75)", type: "leaf" },
          { id: "juz1_baqarah_76_80", label: "Al-Baqarah (76-80)", type: "leaf" },
          { id: "juz1_baqarah_81_85", label: "Al-Baqarah (81-85)", type: "leaf" },
          { id: "juz1_baqarah_86_90", label: "Al-Baqarah (86-90)", type: "leaf" },
          { id: "juz1_baqarah_91_95", label: "Al-Baqarah (91-95)", type: "leaf" },
          { id: "juz1_baqarah_96_100", label: "Al-Baqarah (96-100)", type: "leaf" },
          { id: "juz1_baqarah_101_105", label: "Al-Baqarah (101-105)", type: "leaf" },
          { id: "juz1_baqarah_106_110", label: "Al-Baqarah (106-110)", type: "leaf" },
          { id: "juz1_baqarah_111_115", label: "Al-Baqarah (111-115)", type: "leaf" },
          { id: "juz1_baqarah_116_120", label: "Al-Baqarah (116-120)", type: "leaf" },
          { id: "juz1_baqarah_121_125", label: "Al-Baqarah (121-125)", type: "leaf" },
          { id: "juz1_baqarah_126_130", label: "Al-Baqarah (126-130)", type: "leaf" },
          { id: "juz1_baqarah_131_135", label: "Al-Baqarah (131-135)", type: "leaf" },
          { id: "juz1_baqarah_136_140", label: "Al-Baqarah (136-140)", type: "leaf" },
          { id: "juz1_baqarah_141", label: "Al-Baqarah (141)", type: "leaf" },
        ],
      },

      // ========== JUZ 30 ==========
      {
        id: "juz_30",
        label: "Juz 30",
        type: "expandable",
        children: [
          { id: "juz30_annaba", label: "An-Naba (1-40)", type: "leaf" },
          { id: "juz30_annaziat", label: "An-Nazi'at (1-46)", type: "leaf" },
          { id: "juz30_abasa", label: "'Abasa (1-42)", type: "leaf" },
          { id: "juz30_attakwir", label: "At-Takwir (1-29)", type: "leaf" },
          { id: "juz30_alinfitar", label: "Al-Infitar (1-19)", type: "leaf" },
          { id: "juz30_almutaffifin", label: "Al-Mutaffifin (1-36)", type: "leaf" },
          { id: "juz30_alinsyiqaq", label: "Al-Insyiqaq (1-25)", type: "leaf" },
          { id: "juz30_alburuj", label: "Al-Buruj (1-22)", type: "leaf" },
          { id: "juz30_attariq", label: "At-Tariq (1-17)", type: "leaf" },
          { id: "juz30_alala", label: "Al-A'la (1-19)", type: "leaf" },
          { id: "juz30_alghasyiyah", label: "Al-Gasyiyah (1-26)", type: "leaf" },
          { id: "juz30_alfajr", label: "Al-Fajr (1-30)", type: "leaf" },
          { id: "juz30_albalad", label: "Al-Balad (1-20)", type: "leaf" },
          { id: "juz30_asyams", label: "Asy-Syams (1-15)", type: "leaf" },
          { id: "juz30_allail", label: "Al-Lail (1-21)", type: "leaf" },
          { id: "juz30_adduha", label: "Ad-Duha (1-11)", type: "leaf" },
          { id: "juz30_asyarh", label: "Asy-Syarh (1-8)", type: "leaf" },
          { id: "juz30_attin", label: "At-Tin (1-8)", type: "leaf" },
          { id: "juz30_alalaq", label: "Al-'Alaq (1-19)", type: "leaf" },
          { id: "juz30_alqadr", label: "Al-Qadr (1-5)", type: "leaf" },
          { id: "juz30_albayyinah", label: "Al-Bayyinah (1-8)", type: "leaf" },
          { id: "juz30_azzalzalah", label: "Az-Zalzalah (1-8)", type: "leaf" },
          { id: "juz30_aladiyat", label: "Al-'Adiyat (1-11)", type: "leaf" },
          { id: "juz30_alqariah", label: "Al-Qari'ah (1-11)", type: "leaf" },
          { id: "juz30_attakasur", label: "At-Takasur (1-8)", type: "leaf" },
          { id: "juz30_alasr", label: "Al-'Asr (1-3)", type: "leaf" },
          { id: "juz30_alhumazah", label: "Al-Humazah (1-9)", type: "leaf" },
          { id: "juz30_alfil", label: "Al-Fil (1-5)", type: "leaf" },
          { id: "juz30_quraisy", label: "Quraisy (1-4)", type: "leaf" },
          { id: "juz30_almaun", label: "Al-Ma'un (1-7)", type: "leaf" },
          { id: "juz30_alkausar", label: "Al-Kausar (1-3)", type: "leaf" },
          { id: "juz30_alkafirun", label: "Al-Kafirun (1-6)", type: "leaf" },
          { id: "juz30_annasr", label: "An-Nasr (1-3)", type: "leaf" },
          { id: "juz30_allahab", label: "Al-Lahab (1-5)", type: "leaf" },
          { id: "juz30_alikhlas", label: "Al-Ikhlas (1-4)", type: "leaf" },
          { id: "juz30_alfalaq", label: "Al-Falaq (1-5)", type: "leaf" },
          { id: "juz30_annas", label: "An-Nas (1-6)", type: "leaf" },
        ],
      },

      // ========== JUZ 29 ==========
      {
        id: "juz_29",
        label: "Juz 29",
        type: "expandable",
        children: [
          { id: "juz29_almulk", label: "Al-Mulk (1-30)", type: "leaf" },
          { id: "juz29_alqalam", label: "Al-Qalam (1-52)", type: "leaf" },
          { id: "juz29_alhaqqah", label: "Al-Haqqah (1-52)", type: "leaf" },
          { id: "juz29_almaarij", label: "Al-Ma'arij (1-44)", type: "leaf" },
          { id: "juz29_nuh", label: "Nuh (1-28)", type: "leaf" },
          { id: "juz29_aljinn", label: "Al-Jinn (1-28)", type: "leaf" },
          { id: "juz29_almuzzammil", label: "Al-Muzzammil (1-20)", type: "leaf" },
          { id: "juz29_almuddassir", label: "Al-Muddassir (1-56)", type: "leaf" },
          { id: "juz29_alqiyamah", label: "Al-Qiyamah (1-40)", type: "leaf" },
          { id: "juz29_alinsan", label: "Al-Insan (1-31)", type: "leaf" },
          { id: "juz29_almursalat", label: "Al-Mursalat (1-50)", type: "leaf" },
        ],
      },

      // ========== JUZ 28 ==========
      {
        id: "juz_28",
        label: "Juz 28",
        type: "expandable",
        children: [
          { id: "juz28_almujadilah", label: "Al-Mujadilah (1-22)", type: "leaf" },
          { id: "juz28_alhasyr", label: "Al-Hasyr (1-24)", type: "leaf" },
          { id: "juz28_almumtahanah", label: "Al-Mumtahanah (1-13)", type: "leaf" },
          { id: "juz28_assaff", label: "As-Saff (1-14)", type: "leaf" },
          { id: "juz28_aljumuah", label: "Al-Jumu'ah (1-11)", type: "leaf" },
          { id: "juz28_almunafiqun", label: "Al-Munafiqun (1-11)", type: "leaf" },
          { id: "juz28_attagabun", label: "At-Tagabun (1-18)", type: "leaf" },
          { id: "juz28_attalaq", label: "At-Talaq (1-12)", type: "leaf" },
          { id: "juz28_attahrim", label: "At-Tahrim (1-12)", type: "leaf" },
        ],
      },

      // ========== JUZ 27 ==========
      {
        id: "juz_27",
        label: "Juz 27",
        type: "expandable",
        children: [
          { id: "juz27_alqamar", label: "Al-Qamar (1-55)", type: "leaf" },
          { id: "juz27_arrahman", label: "Ar-Rahman (1-78)", type: "leaf" },
          { id: "juz27_alwaqiah", label: "Al-Waqi'ah (1-96)", type: "leaf" },
          { id: "juz27_alhadid", label: "Al-Hadid (1-29)", type: "leaf" },
        ],
      },

      // ========== JUZ 26 ==========
      {
        id: "juz_26",
        label: "Juz 26",
        type: "expandable",
        children: [
          { id: "juz26_attahrim", label: "At-Tahrim (1-12)", type: "leaf" },
          { id: "juz26_attalaq", label: "At-Talaq (1-12)", type: "leaf" },
          { id: "juz26_attagabun", label: "At-Tagabun (1-18)", type: "leaf" },
          { id: "juz26_almunafiqun", label: "Al-Munafiqun (1-11)", type: "leaf" },
          { id: "juz26_aljumuah", label: "Al-Jumu'ah (1-11)", type: "leaf" },
        ],
      },

      // ========== JUZ 2 ==========
      {
        id: "juz_2",
        label: "Juz 2",
        type: "expandable",
        children: [
          { id: "juz2_baqarah_142_145", label: "Al-Baqarah (142-145)", type: "leaf" },
          { id: "juz2_baqarah_146_150", label: "Al-Baqarah (146-150)", type: "leaf" },
          { id: "juz2_baqarah_151_155", label: "Al-Baqarah (151-155)", type: "leaf" },
          { id: "juz2_baqarah_156_160", label: "Al-Baqarah (156-160)", type: "leaf" },
          { id: "juz2_baqarah_161_165", label: "Al-Baqarah (161-165)", type: "leaf" },
          { id: "juz2_baqarah_166_170", label: "Al-Baqarah (166-170)", type: "leaf" },
          { id: "juz2_baqarah_171_175", label: "Al-Baqarah (171-175)", type: "leaf" },
          { id: "juz2_baqarah_176_180", label: "Al-Baqarah (176-180)", type: "leaf" },
          { id: "juz2_baqarah_181_185", label: "Al-Baqarah (181-185)", type: "leaf" },
          { id: "juz2_baqarah_186_190", label: "Al-Baqarah (186-190)", type: "leaf" },
          { id: "juz2_baqarah_191_195", label: "Al-Baqarah (191-195)", type: "leaf" },
          { id: "juz2_baqarah_196_200", label: "Al-Baqarah (196-200)", type: "leaf" },
          { id: "juz2_baqarah_201_205", label: "Al-Baqarah (201-205)", type: "leaf" },
          { id: "juz2_baqarah_206_210", label: "Al-Baqarah (206-210)", type: "leaf" },
          { id: "juz2_baqarah_211_215", label: "Al-Baqarah (211-215)", type: "leaf" },
          { id: "juz2_baqarah_216_220", label: "Al-Baqarah (216-220)", type: "leaf" },
          { id: "juz2_baqarah_221_225", label: "Al-Baqarah (221-225)", type: "leaf" },
          { id: "juz2_baqarah_226_230", label: "Al-Baqarah (226-230)", type: "leaf" },
          { id: "juz2_baqarah_231_235", label: "Al-Baqarah (231-235)", type: "leaf" },
          { id: "juz2_baqarah_236_240", label: "Al-Baqarah (236-240)", type: "leaf" },
          { id: "juz2_baqarah_241_245", label: "Al-Baqarah (241-245)", type: "leaf" },
          { id: "juz2_baqarah_246_250", label: "Al-Baqarah (246-250)", type: "leaf" },
          { id: "juz2_baqarah_251_252", label: "Al-Baqarah (251-252)", type: "leaf" },
        ],
      },

      // ========== JUZ 3 ==========
      {
        id: "juz_3",
        label: "Juz 3",
        type: "expandable",
        children: [
          { id: "juz3_baqarah_253_255", label: "Al-Baqarah (253-255)", type: "leaf" },
          { id: "juz3_baqarah_256_260", label: "Al-Baqarah (256-260)", type: "leaf" },
          { id: "juz3_baqarah_261_265", label: "Al-Baqarah (261-265)", type: "leaf" },
          { id: "juz3_baqarah_266_270", label: "Al-Baqarah (266-270)", type: "leaf" },
          { id: "juz3_baqarah_271_275", label: "Al-Baqarah (271-275)", type: "leaf" },
          { id: "juz3_baqarah_276_280", label: "Al-Baqarah (276-280)", type: "leaf" },
          { id: "juz3_baqarah_281_285", label: "Al-Baqarah (281-285)", type: "leaf" },
          { id: "juz3_baqarah_286", label: "Al-Baqarah (286)", type: "leaf" },
          { id: "juz3_alimran_1_5", label: "Ali 'Imran (1-5)", type: "leaf" },
          { id: "juz3_alimran_6_10", label: "Ali 'Imran (6-10)", type: "leaf" },
          { id: "juz3_alimran_11_15", label: "Ali 'Imran (11-15)", type: "leaf" },
          { id: "juz3_alimran_16_20", label: "Ali 'Imran (16-20)", type: "leaf" },
          { id: "juz3_alimran_21_25", label: "Ali 'Imran (21-25)", type: "leaf" },
          { id: "juz3_alimran_26_30", label: "Ali 'Imran (26-30)", type: "leaf" },
          { id: "juz3_alimran_31_35", label: "Ali 'Imran (31-35)", type: "leaf" },
          { id: "juz3_alimran_36_40", label: "Ali 'Imran (36-40)", type: "leaf" },
          { id: "juz3_alimran_41_45", label: "Ali 'Imran (41-45)", type: "leaf" },
          { id: "juz3_alimran_46_50", label: "Ali 'Imran (46-50)", type: "leaf" },
          { id: "juz3_alimran_51_55", label: "Ali 'Imran (51-55)", type: "leaf" },
          { id: "juz3_alimran_56_60", label: "Ali 'Imran (56-60)", type: "leaf" },
          { id: "juz3_alimran_61_65", label: "Ali 'Imran (61-65)", type: "leaf" },
          { id: "juz3_alimran_66_70", label: "Ali 'Imran (66-70)", type: "leaf" },
          { id: "juz3_alimran_71_75", label: "Ali 'Imran (71-75)", type: "leaf" },
          { id: "juz3_alimran_76_80", label: "Ali 'Imran (76-80)", type: "leaf" },
          { id: "juz3_alimran_81_85", label: "Ali 'Imran (81-85)", type: "leaf" },
          { id: "juz3_alimran_86_90", label: "Ali 'Imran (86-90)", type: "leaf" },
          { id: "juz3_alimran_91_92", label: "Ali 'Imran (91-92)", type: "leaf" },
        ],
      },

      // ========== JUZ 4 ==========
      {
        id: "juz_4",
        label: "Juz 4",
        type: "expandable",
        children: [
          { id: "juz4_alimran_93_95", label: "Ali 'Imran (93-95)", type: "leaf" },
          { id: "juz4_alimran_96_100", label: "Ali 'Imran (96-100)", type: "leaf" },
          { id: "juz4_alimran_101_105", label: "Ali 'Imran (101-105)", type: "leaf" },
          { id: "juz4_alimran_106_110", label: "Ali 'Imran (106-110)", type: "leaf" },
          { id: "juz4_alimran_111_115", label: "Ali 'Imran (111-115)", type: "leaf" },
          { id: "juz4_alimran_116_120", label: "Ali 'Imran (116-120)", type: "leaf" },
          { id: "juz4_alimran_121_125", label: "Ali 'Imran (121-125)", type: "leaf" },
          { id: "juz4_alimran_126_130", label: "Ali 'Imran (126-130)", type: "leaf" },
          { id: "juz4_alimran_131_135", label: "Ali 'Imran (131-135)", type: "leaf" },
          { id: "juz4_alimran_136_140", label: "Ali 'Imran (136-140)", type: "leaf" },
          { id: "juz4_alimran_141_145", label: "Ali 'Imran (141-145)", type: "leaf" },
          { id: "juz4_alimran_146_150", label: "Ali 'Imran (146-150)", type: "leaf" },
          { id: "juz4_alimran_151_155", label: "Ali 'Imran (151-155)", type: "leaf" },
          { id: "juz4_alimran_156_160", label: "Ali 'Imran (156-160)", type: "leaf" },
          { id: "juz4_alimran_161_165", label: "Ali 'Imran (161-165)", type: "leaf" },
          { id: "juz4_alimran_166_170", label: "Ali 'Imran (166-170)", type: "leaf" },
          { id: "juz4_alimran_171_175", label: "Ali 'Imran (171-175)", type: "leaf" },
          { id: "juz4_alimran_176_180", label: "Ali 'Imran (176-180)", type: "leaf" },
          { id: "juz4_alimran_181_185", label: "Ali 'Imran (181-185)", type: "leaf" },
          { id: "juz4_alimran_186_190", label: "Ali 'Imran (186-190)", type: "leaf" },
          { id: "juz4_alimran_191_195", label: "Ali 'Imran (191-195)", type: "leaf" },
          { id: "juz4_alimran_196_200", label: "Ali 'Imran (196-200)", type: "leaf" },
          { id: "juz4_annisa_1_5", label: "An-Nisa (1-5)", type: "leaf" },
          { id: "juz4_annisa_6_10", label: "An-Nisa (6-10)", type: "leaf" },
          { id: "juz4_annisa_11_15", label: "An-Nisa (11-15)", type: "leaf" },
          { id: "juz4_annisa_16_20", label: "An-Nisa (16-20)", type: "leaf" },
          { id: "juz4_annisa_21_23", label: "An-Nisa (21-23)", type: "leaf" },
        ],
      },

      // ========== JUZ 5 ==========
      {
        id: "juz_5",
        label: "Juz 5",
        type: "expandable",
        children: [
          { id: "juz5_annisa_24_25", label: "An-Nisa (24-25)", type: "leaf" },
          { id: "juz5_annisa_26_30", label: "An-Nisa (26-30)", type: "leaf" },
          { id: "juz5_annisa_31_35", label: "An-Nisa (31-35)", type: "leaf" },
          { id: "juz5_annisa_36_40", label: "An-Nisa (36-40)", type: "leaf" },
          { id: "juz5_annisa_41_45", label: "An-Nisa (41-45)", type: "leaf" },
          { id: "juz5_annisa_46_50", label: "An-Nisa (46-50)", type: "leaf" },
          { id: "juz5_annisa_51_55", label: "An-Nisa (51-55)", type: "leaf" },
          { id: "juz5_annisa_56_60", label: "An-Nisa (56-60)", type: "leaf" },
          { id: "juz5_annisa_61_65", label: "An-Nisa (61-65)", type: "leaf" },
          { id: "juz5_annisa_66_70", label: "An-Nisa (66-70)", type: "leaf" },
          { id: "juz5_annisa_71_75", label: "An-Nisa (71-75)", type: "leaf" },
          { id: "juz5_annisa_76_80", label: "An-Nisa (76-80)", type: "leaf" },
          { id: "juz5_annisa_81_85", label: "An-Nisa (81-85)", type: "leaf" },
          { id: "juz5_annisa_86_90", label: "An-Nisa (86-90)", type: "leaf" },
          { id: "juz5_annisa_91_95", label: "An-Nisa (91-95)", type: "leaf" },
          { id: "juz5_annisa_96_100", label: "An-Nisa (96-100)", type: "leaf" },
          { id: "juz5_annisa_101_105", label: "An-Nisa (101-105)", type: "leaf" },
          { id: "juz5_annisa_106_110", label: "An-Nisa (106-110)", type: "leaf" },
          { id: "juz5_annisa_111_115", label: "An-Nisa (111-115)", type: "leaf" },
          { id: "juz5_annisa_116_120", label: "An-Nisa (116-120)", type: "leaf" },
          { id: "juz5_annisa_121_125", label: "An-Nisa (121-125)", type: "leaf" },
          { id: "juz5_annisa_126_130", label: "An-Nisa (126-130)", type: "leaf" },
          { id: "juz5_annisa_131_135", label: "An-Nisa (131-135)", type: "leaf" },
          { id: "juz5_annisa_136_140", label: "An-Nisa (136-140)", type: "leaf" },
          { id: "juz5_annisa_141_147", label: "An-Nisa (141-147)", type: "leaf" },
        ],
      },
    ],
  },

  // ========== BISNIS ==========
  {
    id: "bisnis",
    label: "💼 Bisnis",
    type: "expandable",
    children: [
      {
        id: "bisnis_sept",
        label: "September 2026",
        type: "expandable",
        children: [
          { id: "bisnis_13sep", label: "13 Sept: Revisi Logo", type: "leaf" },
          { id: "bisnis_20sep", label: "20 Sept: Finalisasi Logo", type: "leaf" },
          { id: "bisnis_27sep", label: "27 Sept: Finalisasi Strategic Plan", type: "leaf" },
        ],
      },
      {
        id: "bisnis_okt",
        label: "Oktober 2026",
        type: "expandable",
        children: [
          { id: "bisnis_4okt", label: "4 Okt: Validasi Produk", type: "leaf" },
          { id: "bisnis_11okt", label: "11 Okt: Prototype", type: "leaf" },
          { id: "bisnis_18okt", label: "18 Okt: Uji Pasar", type: "leaf" },
          { id: "bisnis_25okt", label: "25 Okt: Perbaikan", type: "leaf" },
        ],
      },
      {
        id: "bisnis_nov",
        label: "November 2026",
        type: "expandable",
        children: [
          { id: "bisnis_1nov", label: "1 Nov: Persiapan Produksi", type: "leaf" },
          { id: "bisnis_15nov", label: "15 Nov: Produksi Awal", type: "leaf" },
          { id: "bisnis_30nov", label: "30 Nov: Persiapan Launching", type: "leaf" },
        ],
      },
      {
        id: "bisnis_des",
        label: "Desember 2026",
        type: "expandable",
        children: [
          { id: "bisnis_15des", label: "15 Des: Launching", type: "leaf" },
          { id: "bisnis_31des", label: "31 Des: Evaluasi Launching", type: "leaf" },
        ],
      },
    ],
  },

  // ========== REVIEW TEKNIK MESIN ==========
  {
    id: "teknik",
    label: "📐 Review Teknik Mesin",
    type: "expandable",
    children: [
      {
        id: "semester_1",
        label: "Semester 1",
        type: "expandable",
        children: [
          { id: "mtk1", label: "Matematika 1", type: "leaf" },
          { id: "fisika1", label: "Fisika I", type: "leaf" },
          { id: "kimia1", label: "Kimia Dasar", type: "leaf" },
          { id: "gambar_teknik", label: "Gambar Teknik", type: "leaf" },
          { id: "material_teknik", label: "Material Teknik", type: "leaf" },
          { id: "statika_struktur", label: "Statika Struktur", type: "leaf" },
        ],
      },
      {
        id: "semester_2",
        label: "Semester 2",
        type: "expandable",
        children: [
          { id: "mtk2", label: "Matematika Rekayasa II", type: "leaf" },
          { id: "fisika2", label: "Fisika II", type: "leaf" },
          { id: "gambar_mesin", label: "Gambar Mesin", type: "leaf" },
          { id: "proses_manufaktur", label: "Proses Manufaktur", type: "leaf" },
          { id: "termodinamika_teknik", label: "Termodinamika Teknik", type: "leaf" },
        ],
      },
      {
        id: "semester_3",
        label: "Semester 3",
        type: "expandable",
        children: [
          { id: "analisis_teknik", label: "Analisis Teknik", type: "leaf" },
          { id: "perpindahan_kalor", label: "Perpindahan Kalor", type: "leaf" },
          { id: "mekanika_fluida", label: "Mekanika Fluida", type: "leaf" },
          { id: "mekanika_kekuatan_material", label: "Mekanika Kekuatan Material", type: "leaf" },
          { id: "metrologi", label: "Spesifikasi Geometrik & Metrologi Industri", type: "leaf" },
          { id: "pengukuran_teknik", label: "Pengukuran Teknik", type: "leaf" },
        ],
      },
      {
        id: "semester_4",
        label: "Semester 4",
        type: "expandable",
        children: [
          { id: "metode_numerik", label: "Metode Numerik", type: "leaf" },
          { id: "struktur_material", label: "Struktur & Properti Material", type: "leaf" },
          { id: "getaran_mekanik", label: "Getaran Mekanik", type: "leaf" },
          { id: "kinematika_dinamika", label: "Kinematika & Dinamika", type: "leaf" },
          { id: "desain_eksperimen", label: "Desain Eksperimen", type: "leaf" },
          { id: "desain_elemen_mesin", label: "Desain Elemen Mesin", type: "leaf" },
        ],
      },
      {
        id: "semester_5",
        label: "Semester 5",
        type: "expandable",
        children: [
          { id: "metodologi_penelitian", label: "Metodologi Penelitian", type: "leaf" },
          { id: "sistem_penggerak_elektrik", label: "Sistem Penggerak Elektrik", type: "leaf" },
          { id: "mekatronika", label: "Mekatronika", type: "leaf" },
          { id: "proses_manufaktur_lanjut", label: "Proses Manufaktur Lanjut", type: "leaf" },
          { id: "pemilihan_material", label: "Pemilihan Material dan Proses", type: "leaf" },
          { id: "teknik_pengecoran", label: "Teknik Pengecoran & Pengelasan", type: "leaf" },
        ],
      },
      {
        id: "semester_6",
        label: "Semester 6",
        type: "expandable",
        children: [
          { id: "maintenance_reliability", label: "Maintenance & Reliability", type: "leaf" },
          { id: "teknik_kontrol", label: "Teknik Kontrol Otomatik", type: "leaf" },
          { id: "k3_lingkungan", label: "Kesehatan, Keselamatan & Keamanan Lingkungan", type: "leaf" },
          { id: "teknik_pemotongan", label: "Teknik Pemotongan & Pembentukan Logam", type: "leaf" },
          { id: "analisis_kegagalan", label: "Analisis Kegagalan", type: "leaf" },
          { id: "corrosion_control", label: "Corrosion Control & Mitigation", type: "leaf" },
        ],
      },
      {
        id: "semester_7",
        label: "Semester 7",
        type: "expandable",
        children: [
          { id: "analisis_kelayakan", label: "Analisis Kelayakan Proyek", type: "leaf" },
          { id: "desain_produk", label: "Desain Produk", type: "leaf" },
          { id: "analisis_kegagalan_p", label: "Analisis Kegagalan (P)", type: "leaf" },
          { id: "reverse_engineering", label: "Reverse Engineering", type: "leaf" },
          { id: "material_komposit", label: "Material Komposit", type: "leaf" },
          { id: "karakterisasi_material", label: "Karakterisasi Material", type: "leaf" },
          { id: "technopreneurship", label: "Technopreneurship", type: "leaf" },
        ],
      },
      {
        id: "semester_8",
        label: "Semester 8",
        type: "expandable",
        children: [
          { id: "magang_kerja", label: "Magang Kerja", type: "leaf" },
          { id: "seminar_usulan", label: "Seminar Usulan Penelitian", type: "leaf" },
          { id: "seminar_skripsi", label: "Seminar Skripsi", type: "leaf" },
          { id: "skripsi", label: "Skripsi", type: "leaf" },
          { id: "ujian_komprehensif", label: "Ujian Komprehensif Tertulis", type: "leaf" },
        ],
      },
    ],
  },
];